Load stems from file path: My_Stemnnms.csv
# if no valid file path is provided, a new set of stems will be generated

# unit: meters
Pile extent:
  Width: 6
  Height: 2
  Depth: 3

Number of iterations: 10

Random stem generation:

  Number of stems: 600

  # unit: meters
  Length:
    mean: 3
    standard deviation: 0.02

  # unit: centimeters
  Middle stem diameter:
    mean: 15
    standard deviation: 3

  # no unit; factor for a distribution with mean one
  Ellipticity standard deviation: 0.03

  # unit: centimeters per meter
  Stem taper:
    mean: 1
    standard deviation: 0.2

  # unit: centimeters per meter
  Mean bend: 0.0
