File paths:

Number of iterations: 1
# unit: meters
Pile extent:
  Width: 3
  Height: 2
  Depth: 3

Random stem generation:

  Number of stems: 70

  # unit: meters
  Length:
    mean: 3
    standard deviation: 0.02

  # unit: centimeters
  Middle stem diameter:
    mean: 20
    standard deviation: 5

  # no unit; factor for a distribution with mean one
  Ellipticity standard deviation: 0.03

  # unit: centimeters per meter
  Stem taper:
    mean: 0.0
    standard deviation: 0.00

  # unit: centimeters per meter
  Mean bend: 2
